[package]
name = "libwebp-sys"
version = "0.1.0"
authors = ["Masaki Hara <ackie.h.gmai@gmail.com>"]

[dependencies]
cfg-if = "0.1.6"
libc = "0.2.43"

[features]
default = ["1.0.0"]
"0.5.0" = []
"0.6.0" = ["0.5.0"]
"1.0.0" = ["0.6.0"]
